package com.example.BookShop.entity;


import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import javax.persistence.*;
import java.util.Set;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@ApiModel(description = "data model of author entity")
@Table(name = "author")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 1)
    private int id;

    @ApiModelProperty(value = "name of author", example = "Charlie", position = 2)
    @Column(columnDefinition = "VARCHAR(255)")
    private String name;

    @Column(columnDefinition = "VARCHAR(255)")
    private String photo;

    @Column(columnDefinition = "VARCHAR(255)")
    private String slug;

    @Column(columnDefinition = "TEXT")
    private String description;

    @JsonIgnore
    @ManyToMany(mappedBy = "authors")
    //  список книг данного автора
    private Set<Book> books;

    public Author(int id, String name, String photo, String slug, String description) {
        this.id = id;
        this.name = name;
        this.photo = photo;
        this.slug = slug;
        this.description = description;
    }

    @Override
    public String toString() {
        return name;
    }
}